language: android
jdk: oraclejdk8
android:
  components:
    - build-tools-25.0.2
    - android-25
    - tools
    - platform-tools

    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - '.+'
